config/routes.rb
Rails.application.routes.draw do
  post 'actions/follow'

  post 'actions/unfollow'

  post 'actions/like'

  post 'actions/unlike'

  post 'actions/comment'

  post 'actions/uncomment'

  get 'actions/filter'

  get '/', to: 'events#home'

  get 'auth/login'

  get 'auth/register'

  post 'auth/create'

  get 'auth/destroy'

  get 'event/:id', to: 'events#app_show'

  get 'sports/selection', to: 'sports#app_list'
  
  post 'users/create', to: 'users#create'

  post 'user/:id', to: 'users#user_json'

  scope '/admin' do
    get 'events/display_by_sport/:id', to: 'events#display_by_sport'
    
    resources :events
    resources :sports
    resources :users
  end

  get '*unmatched_route', :to => 'application#render_404'

end

app/views/partials/_profil_bar.html.erb
<section class="col-md-12 nopadding top">
  <div class="top-subscribe">
    <div>
    <% unless currentPath("/") %>
      <span class="back"><a href="/" title="Retour vers la home"><i class="icon-fleche"></i>Retour</a></span>
    <% end %>
    <% if session[:user_id] and currentPath("/") %>
      <%= link_to 'Gérer vos abonnements', sports_selection_path, class: "subscriptions" %>
    <% end %>
    </div>
  </div>
  <div class="top-user">
    <% if session[:user_id] %>
      <p>
        <%= link_to session[:user_firstname] + " " + session[:user_lastname], controller: "users", action: "show", id: session[:user_id] %>
      <p>
    <%= image_tag("/uploads/" + session[:user_picture]) %>
    <% else %>
      <%= link_to 'Connectez-vous', auth_login_path, class: "login" %>

      <span class="has-tooltip" data-toggle="tooltip" data-placement="bottom"  title="Et bénéficiez de services personnalisés : abonnements à des sports, filtres de tris…"><%= link_to 'Inscrivez-vous', auth_register_path, class: "register" %></span>
    <% end %>
  </div>
</section>