config/routes.rb
Rails.application.routes.draw do
  post 'actions/follow'

  post 'actions/unfollow'

  post 'actions/like'

  post 'actions/unlike'

  post 'actions/comment'

  post 'actions/uncomment'

  get 'actions/filter'

  get '/', to: 'events#home'

  get 'auth/login'

  get 'auth/register'

  post 'auth/create'

  get 'auth/destroy'

  get 'event/:id', to: 'events#app_show'

  get 'sports/selection', to: 'sports#app_list'
  
  post 'users/create', to: 'users#create'

  post 'user/:id', to: 'users#user_json'

  scope '/admin' do
    get 'events/display_by_sport/:id', to: 'events#display_by_sport'
    
    resources :events
    resources :sports
    resources :users
  end

  get '*unmatched_route', :to => 'application#render_404'

end

app/models/user.rb
require 'digest/md5'

class User < ActiveRecord::Base
  validates :firstname, :lastname, :email, presence: true
  validates :password, presence: true, :on => :create
  validates :email, uniqueness: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  before_create :encrypt
  before_update :encrypt
  has_many :follows
  has_many :sports, :through => :follows
  has_many :likes
  has_many :events, :through => :likes
  has_many :comments

  def self.index
    User.all
  end

  def self.find_one(user_id)
    User.find(user_id) 
  end

  def self.count
    User.all.size()
  end

  def self.delete_one(user_id)
    User.destroy(user_id)
  end

  def self.auth(auth_info)
    password = Digest::MD5.hexdigest(auth_info['password'])
    begin
      user = User.where(email: auth_info['email'], password: password).take!
    rescue ActiveRecord::RecordNotFound 
      user = nil
    end
  end

  private
  def encrypt
    unless self.password == ''
      self.password = Digest::MD5.hexdigest(self.password)
    else
      self.password = User.find(self.id).password
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login_admin, only: [:index, :destroy]
  layout "admin"

  def index
    @users = User.index
  end

  def show
    @user = User.find_one(params[:id])
  end

  def user_json
    @data = {}
    @likes = []

    @user = User.find_one(params[:id])

    @user_likes = @user.likes.take(5)
    @user_likes.each do |like|
      event = {
        'id' => like.event.id,
        'title' => like.event.title
      }
      @likes.push(event)
    end
    @data['user'] = @user
    @data['likes'] = @likes

    render json: @data
  end

  def new
    @user = User.new
    @ranks = RailsTwitterLike::Application::RANKS
  end

  def create
    @user = User.new(user_params);
    if @user.save
      if request.fullpath == '/users/create'
        user = User.auth(user_params)
        session[:user_id] = user.id
        session[:user_rank] = user.rank
        session[:user_firstname] = user.firstname
        session[:user_lastname] = user.lastname
        session[:user_picture] = user.picture
        session[:user_follows] = {}
        redirect_to sports_selection_path
      else
        redirect_to users_path
      end
    else
      @ranks = RailsTwitterLike::Application::RANKS
      if request.fullpath == '/users/create'
        render '/auth/register', :layout => 'application'
      else
        render :new
      end
    end
  end

  def edit
    @ranks = RailsTwitterLike::Application::RANKS
    @user = User.find_one(params[:id])
  end

  def update
    @user = User.find_one(params[:id])

    if params[:user].key?('picture')
      hash = upload(params[:user][:picture], user_params, "picture")
      @user.update(hash)
      session[:user_picture] = hash['picture']
      redirect_to @user
    elsif @user.update_attributes(user_params)
      redirect_to @user
    else
      render :action => 'edit'
    end
  end

  def destroy
    User.delete_one(params[:id])
    redirect_to users_path
  end

  private
  def user_params
    if request.fullpath == '/users/create'
      return params.permit(:firstname, :lastname, :email, :password)
    end
    if !session[:user_rank] || session[:user_rank] == 'user'
      params.require(:user).permit(:firstname, :lastname, :email, :password, :picture => [:filename => [:@tempfile,:@original_filename,:@content_type,:@headers]])
    else
      params.require(:user).permit(:firstname, :lastname, :email, :password, :rank, :picture => [:filename => [:@tempfile,:@original_filename,:@content_type,:@headers]])
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Edit user</h1>
<div class="col-lg-6">
  <%= simple_form_for @user do |f| %>
    <%= f.input :firstname %>
    <%= f.input :lastname %>
    <%= f.input :email %>
    <%= image_tag("/uploads/"+@user.picture, size: "150") %>
    <%= f.file_field(:picture, accept: 'image/png,image/gif,image/jpeg') %>
    <%= f.input :password %>
    <% if session[:user_rank] == "admin" %>
      <%= f.input :rank, :collection => @ranks %>
    <% end %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>
<div class="row">
  <div class="col-lg-6">
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Firstname</th>
            <th>Lastname</th>
            <th>Email</th>
            <th>Show</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.firstname %></td>
              <td><%= user.lastname %></td>
              <td><%= user.email %></td>
              <td>
                <%= link_to "Show", user, :class => "btn btn-xs btn-primary" %>
              </td>
              <td>
                <%= link_to "Edit", edit_user_path(user), :class => "btn btn-xs btn-info" %>
              </td>
              <td>
                <%= button_to "Delete", user, :method => :delete, :class => "btn btn-xs btn-danger" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Create a new user</h1>
<div class="col-lg-6">
  <%= simple_form_for @user do |f| %>
    <%= f.input :firstname %>
    <%= f.input :lastname %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :rank, :collection => @ranks %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.firstname + " "+ @user.lastname %></h1>

<h2><%= @user.email %></h2>
<h3><%= @user.rank %></h3>
<%= link_to "Edit", { :controller =>"users", :action=> "edit" }, :id=> @user, :class=>"btn btn-default" %>