config/routes.rb
Rails.application.routes.draw do
  post 'actions/follow'

  post 'actions/unfollow'

  post 'actions/like'

  post 'actions/unlike'

  post 'actions/comment'

  post 'actions/uncomment'

  get 'actions/filter'

  get '/', to: 'events#home'

  get 'auth/login'

  get 'auth/register'

  post 'auth/create'

  get 'auth/destroy'

  get 'event/:id', to: 'events#app_show'

  get 'sports/selection', to: 'sports#app_list'
  
  post 'users/create', to: 'users#create'

  post 'user/:id', to: 'users#user_json'

  scope '/admin' do
    get 'events/display_by_sport/:id', to: 'events#display_by_sport'
    
    resources :events
    resources :sports
    resources :users
  end

  get '*unmatched_route', :to => 'application#render_404'

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTwitterLike</title>
  <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Back to application", "/", class: "navbar-brand" %>
      </div>
      <!-- Top Menu Items -->
      <ul class="nav navbar-right top-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <% if session[:user_id] %>
            <%= session[:user_firstname] %> <%= session[:user_lastname] %>
          <% end %>
          <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "Logout", controller: "auth", action: "destroy" %>
            </li>
          </ul>
        </li>
      </ul>
      <% if session[:user_rank] == "admin" %>
      <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
          <li>
            <%= link_to "List users", users_path, class: currentPath(users_path) %>
          </li>
          <li>
            <%= link_to "Create user", new_user_path, class: currentPath(new_user_path) %>
          </li>
          <li>
            <%= link_to "List sports", sports_path, class: currentPath(sports_path) %>
          </li>
          <li>
            <%= link_to "Create sport", new_sport_path, class: currentPath(new_sport_path) %>
          </li>
          <li>
            <%= link_to "List events", events_path, class: currentPath(events_path) %>
          </li>
          <li>
            <%= link_to "Create event", new_event_path, class: currentPath(new_event_path) %>
          </li>
        </ul>
      </div>
      <% end %>
    </nav>

    <div id="page-wrapper">

      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-12">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTwitterLike</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <%= yield %>
</html>